import type { Metadata } from "next";
import { Bowlby_One_SC, Markazi_Text } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import { ThemeProvider } from "./context/ThemeProvider";

const bowlbyOneSC = Bowlby_One_SC({
  variable: "--font-bowlbyOneSC",
  weight: "400",
  subsets: ["latin"],
});

const markaziText = Markazi_Text({
  variable: "--font-markaziText",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${bowlbyOneSC.variable} ${markaziText.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
